### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by jjehl** [Fendiproject/Fendi-lower_limbs#1]
Some external reference are missing. For example : hip_left.sldprt use pelvis2.sldasm for distance calibration and the file is not in the repo.

**Comment by PirouetteNeroz** [comment]
it's good now

**Comment by jjehl** [comment]
Hello,
I can't see any changed files ? Did you upload pelvis2.sldasm  or did you fix the reference in a other way ?

**Comment by Alexandre-lefalher** [comment]
it's good now, I upload pelvis2.sldasm in this folder

**Comment by PirouetteNeroz** [comment]
it's good now, I upload pelvis2.sldasm in this folder
